### PR TITLE
Added test for buildTrie

### PR DESCRIPTION
**Pull request by SarahhhC**
Added tests for initial optionals and non-optionals.

### CODE REVIEW

**Comment by nlpenguin** [comment]
@SarahhhC The change looks great to me but what's the context for this change? Did you mean to improve the code coverage of `processor/util/KoreanPos.scala`?

**Comment by MechanicKim** [comment]
@SarahhhC Look!


The red line will be passed if length is larger than 1, but 'A1' and 'E+' is 2!

**Comment by MechanicKim** [comment]
Um... I found something.



I think the red line can not be passed.

**Comment by nlpenguin** [comment]
That actually means we won't need line 123. Just kill the if statement and leave

`s.slice(2, s.length)`

**Comment by SarahhhC** [comment]
@nlpenguin Yes, I tried to improve the code coverage of `processor/util/KoreanPos.scala` but the main cause was that!

**Pull request merged**
